apiVersion: v1
kind: Secret
metadata:
  name: auth-db-credentials
  namespace: ems
  labels:
    app.kubernetes.io/part-of: employee-management-system
type: Opaque
stringData:
  username: auth_app
  password: CHANGE_ME
  root-password: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: ems-db-credentials
  namespace: ems
  labels:
    app.kubernetes.io/part-of: employee-management-system
type: Opaque
stringData:
  username: ems_app
  password: CHANGE_ME
  root-password: CHANGE_ME

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-credentials
  namespace: ems
  labels:
    app.kubernetes.io/part-of: employee-management-system
type: Opaque
stringData:
  secret: CHANGE_ME